/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ementor;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vincenzo
 */
public class Cadastre extends javax.swing.JFrame {
    static ArrayList<Aluno> dadosAluno = new ArrayList();
    static ArrayList<Professor> dadosProfessor = new ArrayList();   
    
    public static void dadosAlunos() {
        DefaultTableModel Tabela = (DefaultTableModel) TabelaAlunos.Tabela_Alunos.getModel();
        for(Aluno obj: dadosAluno) {
            Tabela.addRow(new Object[] {obj.nome, obj.CPF, 
                                        obj.data_nascimento,
                                        obj.telefone,
                                        obj.getMatricula(),
                                        obj.getPeriodo()});
        }
    }
    
    public static void dadosProfessores() {
        DefaultTableModel Tabela = (DefaultTableModel) TabelaProfessores.Tabela_Professores.getModel();
        for(Professor obj: dadosProfessor) {
            Tabela.addRow(new Object[] {obj.nome, obj.CPF, 
                                        obj.data_nascimento,
                                        obj.telefone,
                                        obj.getData_admissao(),
                                        obj.getSalario_bruto()});
        }
    }
    
    
    /**
     * Creates new form Cadastre
     */
    public Cadastre() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Selector = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        TNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TCpf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TData_Nascimento = new javax.swing.JTextField();
        TContato = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TMatricula = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TPeriodo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TData_Admissao = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TSalario_Bruto = new javax.swing.JTextField();
        ButtonCadastro = new javax.swing.JButton();
        ButtonListar = new javax.swing.JButton();
        ButtonAlterar = new javax.swing.JButton();
        Buscar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela de Cadastro");
        setType(java.awt.Window.Type.UTILITY);

        Selector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione uma opção", "Aluno", "Professor" }));
        Selector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectorActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome");

        jLabel2.setText("CPF");

        TCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TCpfActionPerformed(evt);
            }
        });

        jLabel3.setText("Data de Nascimento");

        TData_Nascimento.setToolTipText("");
        TData_Nascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TData_NascimentoActionPerformed(evt);
            }
        });

        jLabel4.setText("Contato");

        jLabel5.setText("Matrícula");

        jLabel6.setText("Período");

        jLabel7.setText("Data Admissão");

        TData_Admissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TData_AdmissaoActionPerformed(evt);
            }
        });

        jLabel8.setText("Salário bruto");

        ButtonCadastro.setText("Cadastrar");
        ButtonCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCadastroActionPerformed(evt);
            }
        });

        ButtonListar.setText("Listar");
        ButtonListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonListarActionPerformed(evt);
            }
        });

        ButtonAlterar.setText("Alterar");
        ButtonAlterar.setEnabled(false);
        ButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAlterarActionPerformed(evt);
            }
        });

        Buscar.setText("Buscar por CPF");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ementor/icons8-mulher-estudante-48.png"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ementor/icons8-professor-48.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Selector, 0, 176, Short.MAX_VALUE)
                    .addComponent(TMatricula)
                    .addComponent(TContato)
                    .addComponent(TData_Nascimento)
                    .addComponent(TNome)
                    .addComponent(TCpf)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(TPeriodo))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(TData_Admissao)
                    .addComponent(Buscar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(ButtonListar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButtonAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
                    .addComponent(ButtonCadastro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TSalario_Bruto, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel10))))
                .addGap(63, 63, 63))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Selector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TData_Admissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TSalario_Bruto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TData_Nascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Buscar)
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ButtonListar)
                            .addComponent(ButtonAlterar))
                        .addGap(18, 18, 18)
                        .addComponent(ButtonCadastro)))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        TMatricula.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TData_NascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TData_NascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TData_NascimentoActionPerformed

    private void TData_AdmissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TData_AdmissaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TData_AdmissaoActionPerformed

    private void SelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectorActionPerformed
        if(Selector.getSelectedIndex()==0) {
            jLabel9.setVisible(true);
            jLabel10.setVisible(true);
            
            ButtonAlterar.setEnabled(false);
            
            TNome.setText("");
            TData_Nascimento.setText("");
            TContato.setText("");
            TData_Admissao.setText("");
            TSalario_Bruto.setText("");
            TMatricula.setText("");
            TPeriodo.setText("");
            TCpf.setText("");
        }
        if(Selector.getSelectedIndex()==1) {
            jLabel5.setVisible(true);
            TMatricula.setVisible(true);
            jLabel6.setVisible(true);
            TPeriodo.setVisible(true);
         
            jLabel7.setVisible(false);
            TData_Admissao.setVisible(false);
            jLabel8.setVisible(false);
            TSalario_Bruto.setVisible(false);
            
            jLabel9.setVisible(true);
            jLabel10.setVisible(false);
            
            ButtonAlterar.setEnabled(false);
            
            TNome.setText("");
            TData_Nascimento.setText("");
            TContato.setText("");
            TData_Admissao.setText("");
            TSalario_Bruto.setText("");
            TMatricula.setText("");
            TPeriodo.setText("");
            TCpf.setText("");
        } 
        if(Selector.getSelectedIndex()==2) {
            jLabel5.setVisible(false);
            TMatricula.setVisible(false);
            jLabel6.setVisible(false);
            TPeriodo.setVisible(false);
         
            jLabel7.setVisible(true);
            TData_Admissao.setVisible(true);
            jLabel8.setVisible(true);
            TSalario_Bruto.setVisible(true);
            
            jLabel9.setVisible(false);
            jLabel10.setVisible(true);
            
            ButtonAlterar.setEnabled(false);
            
            TNome.setText("");
            TData_Nascimento.setText("");
            TContato.setText("");
            TData_Admissao.setText("");
            TSalario_Bruto.setText("");
            TMatricula.setText("");
            TPeriodo.setText("");
            TCpf.setText("");
        }
    }//GEN-LAST:event_SelectorActionPerformed

    private void ButtonCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCadastroActionPerformed
        if(Selector.getSelectedIndex()==0) {
            JOptionPane.showMessageDialog(null,"Nenhuma opção foi selecionada!","ERRO",JOptionPane.ERROR_MESSAGE);
        }
        if(Selector.getSelectedIndex()==1) {
            if(TNome.getText().isEmpty() || TCpf.getText().isEmpty() || TContato.getText().isEmpty() || TData_Nascimento.getText().isEmpty() || TMatricula.getText().isEmpty() || TPeriodo.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null,"Dados de cadastro incompletos!","ERRO",JOptionPane.ERROR_MESSAGE);
            } else {
                int Matricula = Integer.parseInt(TMatricula.getText());
                int Periodo = Integer.parseInt(TPeriodo.getText());
                long CPF = Long.parseLong(TCpf.getText());

                ConexoesMySQL conec = new ConexoesMySQL();
                conec.insereDadosNoMySQL(TNome.getText(), CPF, TContato.getText(), TData_Nascimento.getText(), Matricula, Periodo);
            }
        }
        if(Selector.getSelectedIndex()==2) {
            if(TNome.getText().isEmpty() || TCpf.getText().isEmpty() || TContato.getText().isEmpty() || TData_Nascimento.getText().isEmpty() || TData_Admissao.getText().isEmpty() || TSalario_Bruto.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null,"Dados de cadastro incompletos!","ERRO",JOptionPane.ERROR_MESSAGE);
            } else {
                double Salario_bruto = Double.parseDouble(TSalario_Bruto.getText());
                long CPF = Long.parseLong(TCpf.getText());
            
                ConexoesMySQL conec = new ConexoesMySQL();
                conec.insereDadosProfessorNoMySQL(TNome.getText(), CPF, TContato.getText(), TData_Nascimento.getText(), TData_Admissao.getText(), Salario_bruto);
            }
        }
    }//GEN-LAST:event_ButtonCadastroActionPerformed

    private void ButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAlterarActionPerformed
        if(Selector.getSelectedIndex()==0) {
            JOptionPane.showMessageDialog(null,"Nenhuma opção foi selecionada!","ERRO",JOptionPane.ERROR_MESSAGE);
        }
        if(Selector.getSelectedIndex()==1) {
            ConexoesMySQL conec = new ConexoesMySQL();
            
            conec.atualizaDadosNoMySQL(TCpf.getText(), TMatricula.getText(), TPeriodo.getText());
        }
        if(Selector.getSelectedIndex()==2) {
            double Salario_bruto = Double.parseDouble(TSalario_Bruto.getText());
            ConexoesMySQL conec = new ConexoesMySQL();
            conec.atualizaDadosProfessorNoMySQL(TCpf.getText(), TData_Admissao.getText(), Salario_bruto);
        }
    }//GEN-LAST:event_ButtonAlterarActionPerformed

    private void ButtonListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonListarActionPerformed
        if(Selector.getSelectedIndex()==0) {
            JOptionPane.showMessageDialog(null,"Nenhuma opção foi selecionada!","ERRO",JOptionPane.ERROR_MESSAGE);
        }
        if(Selector.getSelectedIndex()==1) {
            TabelaAlunos newTabela = new TabelaAlunos();
            newTabela.setVisible(true);
        }
        if(Selector.getSelectedIndex()==2) {
            TabelaProfessores newTabela = new TabelaProfessores();
            newTabela.setVisible(true);
        }
    }//GEN-LAST:event_ButtonListarActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        if(Selector.getSelectedIndex()==0) {
            JOptionPane.showMessageDialog(null,"Nenhuma opção foi selecionada!","ERRO",JOptionPane.ERROR_MESSAGE);
        }
        if(Selector.getSelectedIndex()==1) {
            ConexoesMySQL conec = new ConexoesMySQL();
            Aluno aluno = null;
            
            if(TCpf.getText() != "") {
                aluno = conec.buscaAluno(TCpf.getText());
                ButtonAlterar.setEnabled(true);
            }
            
            if(aluno == null) {
                JOptionPane.showMessageDialog(null,"Aluno não encontrado!","ERRO",JOptionPane.ERROR_MESSAGE);
            } else {
                String Matricula = String.valueOf(aluno.getMatricula());
                String Periodo = String.valueOf(aluno.getPeriodo());

                TNome.setText(aluno.getNome());
                TData_Nascimento.setText(aluno.getData_nascimento());
                TContato.setText(aluno.getTelefone());
                TMatricula.setText(Matricula);
                TPeriodo.setText(Periodo);
            }
        }
         if(Selector.getSelectedIndex()==2) {
            ConexoesMySQL conec = new ConexoesMySQL();
            Professor professor = null;
            if(TCpf.getText() != "") {
                professor = conec.buscaProfessor(TCpf.getText());
                ButtonAlterar.setEnabled(true);
            }
            
            if(professor == null) {
                JOptionPane.showMessageDialog(null,"Professor não encontrado!","ERRO",JOptionPane.ERROR_MESSAGE);
            } else {
                String Data_admissao = String.valueOf(professor.getData_admissao());
                String Salario_bruto = String.valueOf(professor.getSalario_bruto());

                TNome.setText(professor.getNome());
                TData_Nascimento.setText(professor.getData_nascimento());
                TContato.setText(professor.getTelefone());
                TData_Admissao.setText(Data_admissao);
                TSalario_Bruto.setText(Salario_bruto);
            }
        }
    }//GEN-LAST:event_BuscarActionPerformed

    private void TCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TCpfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JButton ButtonAlterar;
    private javax.swing.JButton ButtonCadastro;
    private javax.swing.JButton ButtonListar;
    protected static javax.swing.JComboBox<String> Selector;
    private javax.swing.JTextField TContato;
    private javax.swing.JTextField TCpf;
    private javax.swing.JTextField TData_Admissao;
    private javax.swing.JTextField TData_Nascimento;
    private javax.swing.JTextField TMatricula;
    private javax.swing.JTextField TNome;
    private javax.swing.JTextField TPeriodo;
    private javax.swing.JTextField TSalario_Bruto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
